# Generated by Django 3.0.3 on 2020-04-25 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_compile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='compile',
            new_name='compile_post',
        ),
    ]
